### ISSUE TITLE
"build-and-push-image" command cannot be run within a Docker executor

### ISSUE THREAD

**Issue by christophersansone** [CircleCI-Public/aws-ecr-orb#123]
### Orb version

6.14.0

### What happened

I attempted to run `build-and-push-image` as a command, and it kept failing with a `cannot connect to Docker` error.  When I ran it as a standalone job, it worked.  I finally figured out the problem was that the command cannot be run within a job that uses Docker as the executor.  I changed the job to use a machine image (specifically `ubuntu-2004:202010-01`) and that solved it.

I am using the `aws-cli` and `aws-ecs` orbs extensively as well, and they work great within the Docker executor.

### Expected behavior

Ideally it would be able to run under any executor, so others don't run into the same issue.  If not possible or not worth the effort, just a simple blurb in the Readme to indicate this requirement would be super helpful.

Thanks so much!

**Comment by EricRibeiro** [comment]
Hi @christophersansone

Thanks for getting in touch. By default, the _aws-ecr-orb_ uses a virtual machine as its [executor](https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/executors/default.yml). That's why it is working for you as a standalone job but not with docker.

To use it with a docker executor, you need to set the parameter [setup-remote-docker](https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build-and-push-image.yml#L9) to _true_, and this should do the trick.

If you are still having issues after changing the parameter, I'll be glad to reopen this issue and investigate further.
