### ISSUE TITLE
Add param role-arn in ecr login

### ISSUE THREAD

**Issue by zackssssss** [CircleCI-Public/aws-ecr-orb#158]
## What would you like to be added

I want to add role-arn parameters for using AWS STS.

## Why is this needed

Without role-arn, I can't assume-role for STS and would occur this problem as below. If there is any other ways to resolve this problem, plz give me some information, I really appreciate it!

![image](https://user-images.githubusercontent.com/33366770/132793422-91f1f335-2dc7-40ff-97fd-c312368cf3eb.png)

**Comment by brivu** [comment]
Hey @zackssssss, 

I'm Brian from CircleCI's CPE Team.  I just wanted to let you know that I'm investigating this issue. I have to make some changes to the AWS CLI orb in order to update the `source_profile' with more than just the arn.  I'm hoping to have this fixed soon! 

Thanks for your contribution! 
Brian

**Comment by Ogaday** [comment]
@brivu can you take a look at #170? That might be sufficient as is.

**Comment by brivu** [comment]
@Ogaday - You are correct.  I have to fix the CLI orb in order to fix #170 in the ECR orb

Looking to have a PR ready tomorrow with all of the fixes in place!

**Comment by brivu** [comment]
Hey Cal! 

This issue has been addressed and merged in this PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/172

Cheers! 
Brian
