### ISSUE TITLE
Fails to push to ECR public with docker executor cimg/base:current image

### ISSUE THREAD

**Issue by mtsmfm** [CircleCI-Public/aws-ecr-orb#227]
### Orb version

8.1.2

### What happened

I got the following error when I ran `aws-ecr/build-and-push-image` with docker executor and cimg/base:current image.

```
error: Error response from daemon: unsupported: Invalid parameter at 'registryAliasName' failed to satisfy constraint: 'Member must satisfy regular expression pattern: [a-z][a-z0-9]+(?:[._-][a-z0-9]+)*'
```

Changing executor fixes this problem:

```diff
 build-and-push-docker-image-prd:
-  docker:
-    - image: cimg/base:current
+  machine:
+    image: ubuntu-2004:202107-02
 
   steps:
     - checkout
-    - setup_remote_docker
 
     - when:
         condition: ...
         steps:
           - aws-ecr/build-and-push-image:
```

### Expected behavior

Pushing image without error

**Comment by brivu** [comment]
Hey @mtsmfm, 

I ran into the same issue. AWS ECR just changed their URI scheme. Instead of using an account id like so`public.ecr.aws/${!PARAM_ACCOUNT_ID}`, they have assigned an account alias for each registry so the new scheme looks like this: `public.ecr.aws/registry_alias`

I've added the `public-registry-alias` to the orb in PR #235. If you are pushing to an public registry, you need to provide provide the command or job with the `public-registry-alias`. 

You can find the `default alias` by navigating to the `ECR Management Console` and clicking on `Public Registry`

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/64455338/197063441-065e8f82-5343-4292-a370-4941f759ba82.png">
