### ISSUE TITLE
Your authorization token has expired. Reauthenticate and try again on Self-Hosted Runner

### ISSUE THREAD

**Issue by colinbjohnson** [CircleCI-Public/aws-ecr-orb#265]
### Orb version

`circleci/aws-ecr@8.2.1`

### What happened

When running the `build-and-push-image` job on a self-hosted runner the following error occurs `ERROR: denied: Your authorization token has expired. Reauthenticate and try again.`. This occurs (presumably) 12 hours after the first job using either `build-and-push-image` or the first time the command `ecr-login` is used to run a job that pushes to a particular repository id.

The cause of this error seems to be that:

1. a file is created at `~/.docker/config.json` that contains a token with an expiration period exactly 12 hours in the future (you can base64 decode the token to see the field `"expiration":1675924102`.
2. since this file (and token) is used for subsequent runs
3. the user of the `ecr-login` command attempts to authenticate using the expired token

### Expected behavior

A lot of options are available here and I'm not sure what the right option is:

1. We've worked around by removing the offending file every 12 hours.
2. A `docker logout` command could be issued prior to running the `docker login` command (example: `docker logout 123456789012.dkr.ecr.us-west-2.amazonaws.com`)
3. The `~/.docker/config.json` file could be removed.
4. The path of the ``~/.docker/config.json` file could be changed by running the command like `aws ecr get-login-password --region us-west-2 | docker --config ./ login --username AWS --password-stdin 123456789012.dkr.ecr.us-west-2.amazonaws.com` which could then be placed in the workspace itself (might be dangerous to have this file accessible in a workspace though)
5. Run the `docker login` command each time to refresh the token.

Of all of the above, I think the idea of logging out of the repo prior to creating the file is ideal - this also removes the need to see if the file exists or not.

1. If the file exists (or does not exist) we remove the login information no matter what
2. We generate a new token every time `ecr-login` is called

**Comment by colinbjohnson** [comment]
BTW - we'd be happy to test and PR either a `docker logout/docker login` or repeated `docker login` PR or something better than either of those ideas.

**Comment by brivu** [comment]
Hey @colinbjohnson, 

Thanks for the detailed explanation and potential solution. Just so I understand correctly, after the token expires, the user tries to log in again but since there's already a token that exists in the `~/.docker/config.json` file, the login fails because the token has already expired and is no longer invalid. 

What you're proposing is to run the `docker logout` command before running the `docker login` command [here](https://github.com/CircleCI-Public/aws-ecr-orb/blob/2e79ebaaa025c7cf4ca12b7a4698ee4eada22778/src/scripts/ecr_login.sh#L26) so that any existing token in the `~/.docker/config.json` is removed, correct? 

Please let me know if I am missing anything. In the meantime, I'll add a `PR` for this issue and would appreciate if you can test it for me when it's released. 

Thank you!
Best, 
Brian
