### ISSUE TITLE
Improve performance with --cache-from

### ISSUE THREAD

**Issue by bessey** [CircleCI-Public/aws-ecr-orb#4]
If there was an option to use docker build's --cache-from here:
https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/orb.yml#L73
It would presumably cut build time significantly in the same way Circle's proprietary layer caching does, but more reliably

Reference:
https://semaphoreci.com/docs/docker/docker-layer-caching.html
https://docs.docker.com/edge/engine/reference/commandline/build/

**Comment by RanadeepPolavarapu** [comment]
I'll take this.

**Comment by KyleTryon** [comment]
I may be incorrect here, attempting to look into this. I do not believe this will have any effect as (i think) the docker image you are sourcing for as a cache would need to be in the container in the first place, meaning you would have to first pull it and then use it as a cache. 

If that is incorrect I would love to be wrong!

**Comment by RanadeepPolavarapu** [comment]
Hi @KyleTryon, I agree with you, in most usecases this would not even apply. 

For very complex usecases, I think this functionality would be particularly useful for using common cache layers for build time intensive `RUN` operations. Off the top of my head, an example I can come up with is if you were trying to compile a C binary from source via GCC because you need that bin as a part of image. That compilation is done via a RUN step which produces a cache layer tagged with a some hash. The time it takes to pull an image which may share the same cache layer (same `RUN` step) is far less than compiling that binary from source. This would be very useful in complex container build scenarios where layers overlap. 

*Hypothetical example*: I have a Go app which depends on the fluent-bit binary. I want to build a container that includes my Go binary and the C fluent-bit binary inside the container. I know there is a fluent-bit image already that exists on public DockerHub that would have compiled this via GCC. Rather than me invoking the same GCC build command via `RUN gcc ...` I could just pull the image and use this cache-from functionality to jump over the compilation step as that layer exists in docker's on-disk layer cache already.

**Comment by KyleTryon** [comment]
That does make sense. Thank you for sharing that explanation.

@RanadeepPolavarapu @vsoch have both submitted PRs to this issue. Though both are slightly different. @vsoch was first as well.

https://github.com/CircleCI-Public/docker-orb/pull/21
https://github.com/CircleCI-Public/docker-orb/pull/16

However, I am more interested in merging whichever we believe makes the most sense.

They are very similar so this is a tough call. With #16 being first and including a useful separate pull command I think I am going to hand the merge over to #16. Both are good pr's and are valid for #hacktoberfest or #orbtoberfest. Thank you both!

**Comment by KyleTryon** [comment]
Actually going to reopen this issue for comment. Sorry about that. 1 concern.

https://github.com/CircleCI-Public/docker-orb/pull/21/files#diff-097aec5fcf12af1d49792323e01f8b6fR86

Automatically pulling the images when using the Cache from parameter seems important.

@vsoch one possible concern I have with your approach is if someone uses the cache from parameter in a custom job but has not also used your pull command in conjunction.

Perhaps we should split the difference in these approaches?

**Comment by vsoch** [comment]
Definitely! I might next some help to get the command right. What (I thought) I had done was add a proper when condition so that if cache_from is used, it will always pull first. E.g.,:

```yaml
  - when:
      name: Pull containers for cache_from
      condition: <<parameters.cache_from>>
      steps:
        - pull:
            containers: <<parameters.cache_from>>
```
I'm a bit confused, because the statement above is defined in "publish" and the step "pull" is what is implementing the core bits for cache_from (which is just a parameter). You are saying this approach won't work, because cache_from can be used in some custom way? Could you give an example of how cache_from (a parameter) could be used without pull, or without publish? It's akin to extra_args - if that helps.

**Comment by RanadeepPolavarapu** [comment]
I went with the following design decisions in both this PR and CircleCI-Public/docker-orb#21:
- Avoid writing an extra pull command as a `docker pull` can be done by the users quite easily and as a pull command *may* fall out of the scope of these orbs which has generally been to assist in the building of images.
- Perform an automatic implicit `docker pull` if the `cache-from` param is not empty and that implicitness declared in the documentation.
- I wanted to avoid using when conditions as Docker allows the `--cache-from` value to empty which means the `--cache-from` is ignored by the docker daemon. Therefore, if the `cache-from` param is empty, there won't be any implicit `docker pull`s and the build command will be `docker build --cache-from "" ...`.

Yes, absolutely, we can split the difference 😄 . I am more than happy to hand over the merge to @vsoch for CircleCI-Public/docker-orb#16.

**Comment by vsoch** [comment]
@RanadeepPolavarapu do you want to help me on #16 to achieve what @KyleTryon is asking? I'm relatively new with the configs here and would really appreciate it!

**Comment by RanadeepPolavarapu** [comment]
@vsoch If you would like, would you want to use my approach from CircleCI-Public/docker-orb#21? It accomplishes what you want, but without the `when` conditionals, it will be less verbose in the configs. If you are open to it, I can push my code to your #16 and co-author us both.

**Comment by vsoch** [comment]
If @KyleTryon can confirm this is the best approach to take - I'm down! And I don't think you can push directly, so ideally you can PR to https://github.com/CircleCI-Public/docker-orb/pull/16 (and that way I can also see the changes, and learn from them). I'd like for us both to be commit authors, if that's okay with you.

**Comment by RanadeepPolavarapu** [comment]
@vsoch Absolutely, I'm cool with that. Once @KyleTryon gives sign off, I'll try to PR them to CircleCI-Public/docker-orb#16.

**Comment by vsoch** [comment]
Awesome! I love Hacktoberfest <3

**Comment by KyleTryon** [comment]
@RanadeepPolavarapu & @vsoch Awwwwwwww yeeeesss. Let's do this.
![](https://media0.giphy.com/media/CjmvTCZf2U3p09Cn0h/giphy.gif)

**Comment by RanadeepPolavarapu** [comment]
Done. Pushed co-authored commit CircleCI-Public/docker-orb@8c42b270751c383507a0cbdbaaf93fd649befb16 at CircleCI-Public/docker-orb#21.   

We can merge CircleCI-Public/docker-orb#21 or @vsoch can cherry-pick that hash onto CircleCI-Public/docker-orb#16. Both will yield the same outcome with co-authored commit.

@vsoch if you prefer to merge CircleCI-Public/docker-orb#16 with that commit instead, you can do the following on your branch:

```bash
git fetch --all
git reset --hard
git cherry-pick 8c42b270751c383507a0cbdbaaf93fd649befb16
git push -f
```

**Comment by vsoch** [comment]
okay let me give that a try! I expected you to open a PR to https://github.com/CircleCI-Public/docker-orb/pull/16 but this works too :)

**Comment by RanadeepPolavarapu** [comment]
@vsoch I couldn't because GH didn't let me. If you want, add me as a contributor to https://github.com/vsoch/docker-orb and I can do so.

**Comment by vsoch** [comment]
@RanadeepPolavarapu I don't think you provided full instructions, since your remote won't be added to my git config?

**Comment by vsoch** [comment]
@RanadeepPolavarapu anyone can open a pull request to another individual's repository - you don't need to be a contributor. I'll look over the changes and then merge into my branch. I'd prefer doing this over the cherry pick kung fu.

**Comment by vsoch** [comment]
Once you do the PR and we merge to the branch `add/docker-cache` it will update the PR automatically - this seems like the cleanest approach to take.

**Comment by RanadeepPolavarapu** [comment]
> Once you do the PR and we merge to the branch `add/docker-cache` it will update the PR automatically - this seems like the cleanest approach to take.

Done. https://github.com/vsoch/docker-orb/pull/2

**Comment by vsoch** [comment]
Why are there conflicts?

**Comment by RanadeepPolavarapu** [comment]
@vsoch Your approach uses `when` conditions. Mine doesn't that's why the conflicts are appearing. You can reset your branch and conflicts will disappear. `git reset --hard origin/master && git push -f` then you can merge the PR with no conflicts.

**Comment by vsoch** [comment]
If you start cleanly from the branch, make changes, and commit, there shouldn't be.

**Comment by RanadeepPolavarapu** [comment]
Done. Conflicts resolved https://github.com/vsoch/docker-orb/pull/2 <https://github.com/vsoch/docker-orb/pull/2>.

**Comment by vsoch** [comment]
okay we're combined! https://github.com/CircleCI-Public/docker-orb/pull/16 Take it away @KyleTryon

**Comment by eddiewebb** [comment]
https://github.com/CircleCI-Public/docker-orb/pull/27 addresses this.
