### ISSUE TITLE
Feature request: Support goss test

### ISSUE THREAD

**Issue by ozooxo** [CircleCI-Public/aws-ecr-orb#51]
It will be really nice if we can test our docker image (through goss test) after build the image.

Refer to:

- https://circleci.com/blog/testing-docker-images-with-circleci-and-goss/
- https://github.com/aelsabbahy/goss

**Comment by lokst** [comment]
@ozooxo Could you elaborate on what kind of support you are thinking of? Would it be for the orb to alllow running goss (installing goss if it's not detected) on the built image with a user-provided goss yaml file?

**Comment by ozooxo** [comment]
> Would it be for the orb to alllow running goss (installing goss if it's not detected) on the built image with a user-provided goss yaml file?

@lokst Yup, that's what I was thinking about. Probably provide a flag `goss_enabled` (may be smart that if there's no `goss.yaml` just ignore is flag, otherwise default true) and if enabled, run `dgoss` command at the end of the build process.

Also just realized I pasted the wrong URL in my previous question (also modified now). it is https://circleci.com/blog/testing-docker-images-with-circleci-and-goss/

**Comment by gmemstr** [comment]
I don't know if this addition neccesarily makes sense in the context of the orb - you might be better served with a goss orb (if one exists) with the `build-image` command, which could either be in a job before the `build-and-push-image` workflow or be in a job that uses the `ecr-login` and `push-image` commands. Unless we see a number of requests for this, I don't think it's a good fit, especially since we already offer the flexibility with the commands.

**Comment by KyleTryon** [comment]
Also of the opinion a "goss" orb may be the more flexible solution. It doesnt appear any "Goss" orbs have been created yet but may be a good candidate 👍
