### ISSUE TITLE
Getting error while creating ECR repository using circleci aws-ecr orbs for .NET Framework legacy application

### ISSUE THREAD

**Issue by SinghJ3** [CircleCI-Public/aws-ecr-orb#90]
### Orb version

  **aws-ecr:** circleci/aws-ecr@6.7.0

### What happened

I am using **aws-ecr** obrs to build docker image, create an ECR repository if doesn't exist and push that docker image to ECR repository for **.NET Framework legacy application**. It is executing fine till the step of **Build docker image**. When it is trying to create an ECR repository, it is breaking at this step. It is unable to create ECR repository.

**CircleCI Link:**
https://app.circleci.com/pipelines/github/moodysanalytics/cmm-service/10/workflows/e6dbc71d-e9b0-43eb-9525-870ecacb35cd/jobs/9

### Expected behavior

After building the docker image, it should create an ECR repository and push the docker image to that ECR repository.

**Comment by lokst** [comment]
Hi @SinghJ3 I understand that our Support team is looking into this issue with you. It looks like the problem is due to the aws CLI version installed by `aws-cli` orb not being in the PATH, leading to an older, preinstalled aws CLI version which does not support the `--image-scanning-configuration, scanOnPush=true` options being used.

We plan to update the `aws-cli` orb to support aws CLI v2 soon, and for the `aws-ecr` orb to then use v2 of the aws CLI, so that should help with such PATH issues in the future.

**Comment by gmemstr** [comment]
@SinghJ3 We recently updated this orb to support the v2 of the AWS CLI, can you confirm whether or not you are still experiencing this issue with the latest version of the orb?

**Comment by gmemstr** [comment]
Assuming this is resolved due to the 2.0 CLI, feel free to reopen if this is not the case.
